# Site settings
title: Academic Jyunko
author: 简律纯 
email: i@jyunko.cn
description: AI/ML, thoughts?
# logo: assets/retro.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://academic.jyunko.cn" # the base hostname & protocol for your site
highlighter: rouge
minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: 'github', user_url: "https://github.com/HsiangNianian" }

disqus:
  shortname: cypress-github-io

show_excerpts: true

feed:
  excerpt_only: true

header_pages:
  - publications.md
  - blog.md
  - Links.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# tips
gems: ["tipsy"]

# admin
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"

exclude:
  - "v3"
