# Site settings
title: Academic Jyunko
author: 简律纯
email: HsiangNianian@outlook.com
description: AI/ML, thoughts? 
# logo: assets/retro.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://academic.jyunko.cn" # the base hostname & protocol for your site

social_links:
  twitter: HsiangNianian
  github: HsiangNianian
  facebook: hsiang.nianian
  soundcloud: hsiang_nianian
  instagram: hsiang_nianian 

google_analytics: G-WQVB7M8ZZ2

disqus:
  shortname: cypress-github-io

show_excerpts: true

feed:
  excerpt_only: true

header_pages:
  - publications.md
  - blog.md
  - Links.md
  
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tipsy
  
# tips
tipsy:
  selector: '[data-tipsy]'     # 指定触发提示的元素选择器（这里使用了 HTML5 data-* 属性）
  gravity: n                  # 指定提示文本的位置
  fadeIn: 200                 # 指定提示文本的显示和隐藏动画
  fadeOut: 200
