# Configurations
title:            Academic Jyunko
longtitle:        Academic Jyunko,for AI/ML
author:           简律纯
email:            admin@jyunko.cn
description: >
  AI/ML, thoughts? 

version:          1.0
gitbook_version:  3.2.3

url:              'https://academic.jyunko.cn'
baseurl:          '' #'/jekyll-gitbook'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/retro.png

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

# show_excerpts: true

# social_links:
#   twitter: HsiangNianian
#   github: HsiangNianian
#   facebook: hsiang.nianian
#   soundcloud: hsiang_nianian
#   instagram: hsiang_nianian 

destination:      ./_site
incremental:      false
regenerate:       true

# disqus:
#   shortname: cypress-github-io

# header_pages:
#   - publications.md
#   - blog.md
#   - Links.md

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap