# Site settings
title: Academic Jyunko
author:
  name: 简律纯
  email: i@jyunko.cn
description: AI/ML, thoughts?
# logo: assets/retro.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://academic.jyunko.cn" # the base hostname & protocol for your site

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - { platform: facebook,       user_url: "https://www.facebook.com/hsiang.nianian" }
    - { platform: github,         user_url: "https://github.com/jekyll/HsiangNianian" }
    - { platform: instagram,      user_url: "https://www.instagram.com/hsiang_nianian" }
    - { platform: telegram,       user_url: "https://t.me/Hsiang_Nianian" }
    - { platform: twitter,        user_url: "https://twitter.com/HsiangNianian" }
    - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

google_analytics: G-WQVB7M8ZZ2

disqus:
  shortname: cypress-github-io

show_excerpts: true

feed:
  excerpt_only: true

header_pages:
  - publications.md
  - blog.md
  - Links.md

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# tips
gems: ["tipsy"]
