# Site settings
title: academic jyunko
author: jyunko(简律纯)
email: HsiangNianian@outlook.com
description: AI/ML
logo: assets/HF.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://academic.jyunko.cn" # the base hostname & protocol for your site

social_links:
  twitter: HsiangNianian
  github: cypress0522
  facebook: Hsiang_Nianian

google_analytics: G-WQVB7M8ZZ2

disqus:
  shortname: cypress0522

show_excerpts: true

feed:
  excerpt_only: true

header_pages:
  - publications.md
  - blog.md

# Build settings
markdown: kramdown
# theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
